### ISSUE TITLE
High CPU on tasks that keep the terminal open

### ISSUE THREAD

**Issue by i07** [Gruntfuggly/triggertaskonsave#12] opened 2019-11-01 13:10 UTC
When starting a task that is keeping the terminal open; for example building and running an application, the plugin drives all cpu's to at least 50%. Also if the task isn't started by this plugin.

when the task is run without this plugin enabled; all cpu's remain around 1-2%

Is the watcher going into overdrive?

Another 'more or less related' issue; how do I exclude folders from the watcher; i've tried all kinds of variations with the glob '!' for excluding, but whenever I add a '!' it seems the watcher is watching all files.

my config:

```
"triggerTaskOnSave.on": true,
"triggerTaskOnSave.restart": true,
"triggerTaskOnSave.selectedTask": "Build and run",
"triggerTaskOnSave.tasks": {
	"build": [
		"**/*.go",
	]
}

**Comment by Gruntfuggly** [comment] 2019-11-01 13:19
Can you have a look in the output channel (View->Output and select Trigger Task On Save from the drop down) and see what it is showing when using the CPU? It should only trigger when a file is saved.

The exclude probably doesn't work as you would expect because it just tries to match each glob until it finds one that works. I'll see if I can make a change so that you can add excludes.

**Comment by i07** [comment] 2019-11-01 15:00
Hi Gruntfuggly, thanks for the reply, here is the output from View->Output.

3:56:00 PM vscode.workspace.onDidSaveTextDocument: /home/marc/Development/xxxx/app.go in workspace: marcworkspace
3:56:00 PM {"build":["**/*.go"]}
3:56:00 PM task:build
3:56:00 PM vscode.workspace.onDidSaveTextDocument: match:**/*.go
3:56:00 PM findAndRunTask: executing Build and run
3:56:00 PM vscode.tasks.onDidStartTask Build and run

and nothing else is added, until I press save on a *.go file again, and the output is similar, but adding the onDidEndTask for stopping the previous task.

if I start the task via command palette; then this is added to the output
4:00:03 PM vscode.tasks.onDidStartTask Build and run

and upon breaking the terminal:
4:00:31 PM vscode.tasks.onDidEndTask Build and run

So perhaps the wait for onDidEndTask? just throwing something around ;)

**Comment by i07** [comment] 2019-11-01 15:11
and thanks for looking into an exclude option; I've created another issue for that one.

**Comment by Gruntfuggly** [comment] 2019-11-01 15:23
OK,  that suggests that the extension isn't actually doing anything once the task has started. The only thing I can think of is that the busy indicator (the spinning icon in the status bar) is causing it!? There is a setting to disable it - `triggerTaskOnSave.showBusyIndicator`. Can you see if it makes a difference?

**Comment by i07** [comment] 2019-11-01 15:30
Yes you are right the busy indicator is the source of this issue.

The High CPU issue is solved by setting:
`triggerTaskOnSave.showBusyIndicator: false`

For me this is acceptable, since i'm not in need of the indicator.! Thank you, and hope you can fix it!

**Comment by Gruntfuggly** [comment] 2019-11-01 15:36
It's not part of the extension - it's just an icon that can be specified for a status bar item. Seems weird that it causes such high load though. I might raise an issue on vscode if I can find an easy way to reproduce it. Unfortunately, all my tasks are fairly intensive anyway, so I've never noticed it as an issue.

**Comment by i07** [comment] 2019-11-01 15:42
It would be easy for you to test, this also results in high cpu when triggertaskonsave is active as plugin

task:
```
{
     "label": "Testing",
     "type": "shell",
     "command": "sleep 60",
     "group": {
        "kind": "build",
        "isDefault": true
     },
}
```
and this for the extension:
```
"triggerTaskOnSave.on": true,
"triggerTaskOnSave.restart": true,
"triggerTaskOnSave.selectedTask": "Testing",
"triggerTaskOnSave.showBusyIndicator": true
```

hopes it gives you some insights!

**Comment by Gruntfuggly** [comment] 2019-11-01 15:43
Thanks - I'll give it a try.

**Comment by Gruntfuggly** [comment] 2019-11-01 15:49
OK, tried it but I don't see any increase in CPU (under Ubuntu). Maybe it's something different in your set up?

**Comment by i07** [comment] 2019-11-01 15:52
I'm using

Version: 1.39.0-exploration
Commit: a715df3459718a501686bd03414f69929bf6e9a2
Date: 2019-09-13T06:32:38.451Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-32-generic

on Ubuntu 18.04

**Comment by Gruntfuggly** [comment] 2019-11-01 15:56
Only real difference is that I'm using 1.39.2 on 16.04. That's really odd. Not sure what to suggest...

**Comment by i07** [comment] 2019-11-01 16:00
![image](https://user-images.githubusercontent.com/6317005/68037850-e9f02900-fcc8-11e9-91c1-3871c08acda8.png)

That graph is from running the Testing task from before; made sure nothing else was running. But I think bringing it to vscode dev attention might be worthwhile ;) for me setting the indicator to false suffices.

**Comment by i07** [comment] 2019-11-01 16:08
Just tried it on this one:

Version: 1.40.0-insider
Commit: 37d34176a6ecf1d09b16a0cad11bb619f3b1e48f
Date: 2019-11-01T10:17:00.077Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-32-generic

Still the same; when I do not use the indicator, then it's all good

**Comment by i07** [comment] 2019-11-01 16:44
Perhaps good to know; I'm using KDE Plasma (v5.15.4) as my desktop; I'll try to install another desktop manager and test again, update here when I have some more info

**Comment by i07** [comment] 2019-11-01 17:22
Just tried it on XFCE4, and it does make a difference, however.. as on KDE Plasma the CPU goes up to 50%, on XFCE it goes up to 15%

When I turn off the showBusyIndicator the average CPU on both is between 1 and 3%.

Even though on Plasma it's higher, on XFCE it also shows an significant increase, and just for an busy indicator. ;) ..

**Comment by Gruntfuggly** [comment] 2020-01-31 09:59
Hi - are you still seeing this? If so, it might be worth moving the information in this thread into a vscode issue.

**Comment by Gruntfuggly** [comment] 2020-05-21 20:16
I'm going to close this as it's been 6 months. If it occurs again, feel free to re-open.

**Closed as completed by Gruntfuggly** 2020-05-21 20:16 UTC
Labels: bug
